kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "dima-sample-flask" 
spec:
  runPolicy: "Serial" 
  triggers: 
    -
      type: "ImageChange"
  source: 
    git:
      uri: "https://github.com/mborodin/openshift-sample-build.git"
  strategy: 
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "python:alpine"
  output: 
    to:
      kind: "ImageStreamTag"
      name: "dima-sample-flask:latest"